spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/stock-forum
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

#forum:
#  stock-forum:
#    base:
#      url: http://localhost:8080/dir/

---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://stock-forum-database:3306/stock-forum
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#  redis:
#    host: stock-forum-redis
#    port: 6379
#  jpa:
#    hibernate:
#      ddl-auto: validate # prod 배포시 validate
#    show-sql: true
#
#pharmacy:
#  recommendation:
#    base:
#      url: http://3.38.78.187/dir/