version: "3.8"                                    # 파일 규격 버전
services:                                         # 이 항목 밑에 실행하려는 컨테이너들을 정의
  service-news-feed-redis:                        # 서비스명
    container_name: service-news-feed-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: zcx5674/service-news-feed-redis
    ports:
      - "6379:6379"
  service-news-feed-database:
    container_name: service-news-feed-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: zcx5674/service-news-feed-database
    environment:
      - MONGO_INITDB_DATABASE=service-news-feed
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"